name: Continuous Integration with GitHub Actions
on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: "Enter browser name: "
        default: chrome
      xmlfilename:
        type: string
        description: "Enter .xml file name: "
        default: TestNG.xml
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with TestNG xml files
      run: >
        mvn clean test
        -Dsurefire.suiteXmlFiles=${{inputs.xmlfilename}}
        -DbrowserName=${{inputs.browsername}}
        -Dsurefire.suiteXmlFiles=TestNG.xml
        -DbrowserName=chrome
        -Dplatform=GitHubActions
        -Dmaven.test.failure.ignore=true
#Report Generation
    - name: archive report artifact
      uses: actions/upload-artifact@v4
      with:
        name: sparkHTML
        path: ./reports/*.html
